export const INIT_APP = 'hrv/INIT_APP';
export const APP_SET_TITLE = 'hrv/APP_SET_TITLE';

export const LOGIN_REQUEST = 'hrv/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'hrv/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'hrv/LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'hrv/LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'hrv/LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'hrv/LOGOUT_FAILURE';

export const SOURCE_FAILURE = 'hrv/data/SOURCE_FAILURE';
export const SOURCE_LIST_REQUEST = 'hrv/data/SOURCE_LIST_REQUEST';
export const SOURCE_LIST_SUCCESS = 'hrv/data/SOURCE_LIST_SUCCESS';

export const PROCESSINGMETHOD_FAILURE = 'hrv/data/PROCESSINGMETHOD_FAILURE';
export const PROCESSINGMETHOD_LIST_REQUEST = 'hrv/data/PROCESSINGMETHOD_LIST_REQUEST';
export const PROCESSINGMETHOD_LIST_SUCCESS = 'hrv/data/PROCESSINGMETHOD_LIST_SUCCESS';

export const ANALYSIS_SNAPSHOT_FAILURE = 'hrv/data/ANALYSIS_SNAPSHOT_FAILURE';
export const ANALYSIS_SNAPSHOT_LIST_REQUEST = 'hrv/data/ANALYSIS_SNAPSHOT_LIST_REQUEST';
export const ANALYSIS_SNAPSHOT_LIST_SUCCESS = 'hrv/data/ANALYSIS_SNAPSHOT_LIST_SUCCESS';

export const ANALYSIS_LABEL_FAILURE = 'hrv/data/ANALYSIS_LABEL_FAILURE';
export const ANALYSIS_LABEL_LIST_REQUEST = 'hrv/data/ANALYSIS_LABEL_LIST_REQUEST';
export const ANALYSIS_LABEL_LIST_SUCCESS = 'hrv/data/ANALYSIS_LABEL_LIST_SUCCESS';
export const ANALYSIS_LABEL_CREATE_REQUEST = 'hrv/data/ANALYSIS_LABEL_CREATE_REQUEST';
export const ANALYSIS_LABEL_CREATE_SUCCESS = 'hrv/data/ANALYSIS_LABEL_CREATE_SUCCESS';

export const ANALYSIS_RESULT_FAILURE = 'hrv/data/ANALYSIS_RESULT_FAILURE';
export const ANALYSIS_RESULT_GET_REQUEST = 'hrv/data/ANALYSIS_RESULT_GET_REQUEST';
export const ANALYSIS_RESULT_GET_SUCCESS = 'hrv/data/ANALYSIS_RESULT_GET_SUCCESS';
export const ANALYSIS_RESULT_LIST_REQUEST = 'hrv/data/ANALYSIS_RESULT_LIST_REQUEST';
export const ANALYSIS_RESULT_LIST_SUCCESS = 'hrv/data/ANALYSIS_RESULT_LIST_SUCCESS';
export const ANALYSIS_RESULT_CREATE_REQUEST = 'hrv/data/ANALYSIS_RESULT_CREATE_REQUEST';
export const ANALYSIS_RESULT_CREATE_SUCCESS = 'hrv/data/ANALYSIS_RESULT_CREATE_SUCCESS';
export const ANALYSIS_RESULT_START_POLLING = 'hrv/data/ANALYSIS_RESULT_START_POLLING';
export const ANALYSIS_RESULT_STOP_POLLING = 'hrv/data/ANALYSIS_RESULT_STOP_POLLING';

export const ANALYSIS_SAMPLE_FAILURE = 'hrv/data/ANALYSIS_SAMPLE_FAILURE';
export const ANALYSIS_SAMPLE_CREATE_REQUEST = 'hrv/data/ANALYSIS_SAMPLE_CREATE_REQUEST';
export const ANALYSIS_SAMPLE_CREATE_SUCCESS = 'hrv/data/ANALYSIS_SAMPLE_CREATE_SUCCESS';
export const ANALYSIS_SAMPLE_UPDATE_REQUEST = 'hrv/data/ANALYSIS_SAMPLE_UPDATE_REQUEST';
export const ANALYSIS_SAMPLE_UPDATE_SUCCESS = 'hrv/data/ANALYSIS_SAMPLE_UPDATE_SUCCESS';
export const ANALYSIS_SAMPLE_DESTROY_REQUEST = 'hrv/data/ANALYSIS_SAMPLE_DESTROY_REQUEST';
export const ANALYSIS_SAMPLE_DESTROY_SUCCESS = 'hrv/data/ANALYSIS_SAMPLE_DESTROY_SUCCESS';

export const SUBJECT_FAILURE = 'hrv/data/SUBJECT_FAILURE';
export const SUBJECT_GET_REQUEST = 'hrv/data/SUBJECT_GET_REQUEST';
export const SUBJECT_GET_SUCCESS = 'hrv/data/SUBJECT_GET_SUCCESS';
export const SUBJECT_LIST_REQUEST = 'hrv/data/SUBJECT_LIST_REQUEST';
export const SUBJECT_LIST_SUCCESS = 'hrv/data/SUBJECT_LIST_SUCCESS';
export const SUBJECT_CREATE_REQUEST = 'hrv/data/SUBJECT_CREATE_REQUEST';
export const SUBJECT_CREATE_SUCCESS = 'hrv/data/SUBJECT_CREATE_SUCCESS';
export const SUBJECT_DESTROY_REQUEST = 'hrv/data/SUBJECT_DESTROY_REQUEST';
export const SUBJECT_DESTROY_SUCCESS = 'hrv/data/SUBJECT_DESTROY_SUCCESS';

export const SESSION_FAILURE = 'hrv/data/SESSION_FAILURE';
export const SESSION_GET_REQUEST = 'hrv/data/SESSION_GET_REQUEST';
export const SESSION_GET_SUCCESS = 'hrv/data/SESSION_GET_SUCCESS';
export const SESSION_LIST_REQUEST = 'hrv/data/SESSION_LIST_REQUEST';
export const SESSION_LIST_SUCCESS = 'hrv/data/SESSION_LIST_SUCCESS';
export const SESSION_CREATE_REQUEST = 'hrv/data/SESSION_CREATE_REQUEST';
export const SESSION_CREATE_SUCCESS = 'hrv/data/SESSION_CREATE_SUCCESS';
export const SESSION_DESTROY_REQUEST = 'hrv/data/SESSION_DESTROY_REQUEST';
export const SESSION_DESTROY_SUCCESS = 'hrv/data/SESSION_DESTROY_SUCCESS';

export const DATASET_FAILURE = 'hrv/data/DATASET_FAILURE';
export const DATASET_GET_REQUEST = 'hrv/data/DATASET_GET_REQUEST';
export const DATASET_GET_SUCCESS = 'hrv/data/DATASET_GET_SUCCESS';
export const DATASET_CREATE_REQUEST = 'hrv/data/DATASET_CREATE_REQUEST';
export const DATASET_CREATE_SUCCESS = 'hrv/data/DATASET_CREATE_SUCCESS';
export const DATASET_DESTROY_REQUEST = 'hrv/data/DATASET_DESTROY_REQUEST';
export const DATASET_DESTROY_SUCCESS = 'hrv/data/DATASET_DESTROY_SUCCESS';
export const DATASET_START_POLLING = 'hrv/data/DATASET_START_POLLING';
export const DATASET_STOP_POLLING = 'hrv/data/DATASET_STOP_POLLING';

export const PLOT_UPSERT = 'hrv/PLOT_UPSERT';
export const PLOT_DELETE = 'hrv/PLOT_DELETE';
export const PLOT_SET_MODE = 'hrv/PLOT_SET_MODE';
export const PLOT_SET_DOMAIN = 'hrv/PLOT_SET_DOMAIN';
export const PLOT_SET_TAGS = 'hrv/PLOT_SET_TAGS';

export const ANALYSIS_LABEL_SELECT = 'hrv/ANALYSIS_LABEL_SELECT';
export const ANALYSIS_SNAPSHOT_SELECT = 'hrv/ANALYSIS_SNAPSHOT_SELECT';
export const ANALYSIS_SIGNAL_ADD = 'hrv/ANALYSIS_SIGNAL_ADD';
export const ANALYSIS_SIGNAL_REMOVE = 'hrv/ANALYSIS_SIGNAL_REMOVE';
export const ANALYSIS_METHOD_ADD = 'hrv/ANALYSIS_METHOD_ADD';
export const ANALYSIS_METHOD_REMOVE = 'hrv/ANALYSIS_METHOD_REMOVE';
export const ANALYSIS_METHOD_CONFIG_SET = 'hrv/ANALYSIS_METHOD_CONFIG_SET';
export const ANALYSIS_RUN = 'hrv/ANALYSIS_RUN';
export const ANALYSIS_RESET = 'hrv/ANALYSIS_RESET';
