export const INIT_APP = 'hrv/INIT_APP';
export const APP_SET_TITLE = 'hrv/APP_SET_TITLE';

export const LOGIN_REQUEST = 'hrv/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'hrv/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'hrv/LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'hrv/LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'hrv/LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'hrv/LOGOUT_FAILURE';

export const SOURCE_FAILURE = 'hrv/data/SOURCE_FAILURE';
export const SOURCE_LIST_REQUEST = 'hrv/data/SOURCE_LIST_REQUEST';
export const SOURCE_LIST_SUCCESS = 'hrv/data/SOURCE_LIST_SUCCESS';

export const ANALYSIS_LABEL_FAILURE = 'hrv/data/ANALYSIS_LABEL_FAILURE';
export const ANALYSIS_LABEL_LIST_REQUEST = 'hrv/data/ANALYSIS_LABEL_LIST_REQUEST';
export const ANALYSIS_LABEL_LIST_SUCCESS = 'hrv/data/ANALYSIS_LABEL_LIST_SUCCESS';
export const ANALYSIS_LABEL_CREATE_REQUEST = 'hrv/data/ANALYSIS_LABEL_CREATE_REQUEST';
export const ANALYSIS_LABEL_CREATE_SUCCESS = 'hrv/data/ANALYSIS_LABEL_CREATE_SUCCESS';

export const ANALYSIS_SAMPLE_FAILURE = 'hrv/data/ANALYSIS_SAMPLE_FAILURE';
export const ANALYSIS_SAMPLE_CREATE_REQUEST = 'hrv/data/ANALYSIS_SAMPLE_CREATE_REQUEST';
export const ANALYSIS_SAMPLE_CREATE_SUCCESS = 'hrv/data/ANALYSIS_SAMPLE_CREATE_SUCCESS';
export const ANALYSIS_SAMPLE_UPDATE_REQUEST = 'hrv/data/ANALYSIS_SAMPLE_UPDATE_REQUEST';
export const ANALYSIS_SAMPLE_UPDATE_SUCCESS = 'hrv/data/ANALYSIS_SAMPLE_UPDATE_SUCCESS';
export const ANALYSIS_SAMPLE_DESTROY_REQUEST = 'hrv/data/ANALYSIS_SAMPLE_DESTROY_REQUEST';
export const ANALYSIS_SAMPLE_DESTROY_SUCCESS = 'hrv/data/ANALYSIS_SAMPLE_DESTROY_SUCCESS';

export const SUBJECT_FAILURE = 'hrv/data/SUBJECT_FAILURE';
export const SUBJECT_GET_REQUEST = 'hrv/data/SUBJECT_GET_REQUEST';
export const SUBJECT_GET_SUCCESS = 'hrv/data/SUBJECT_GET_SUCCESS';
export const SUBJECT_LIST_REQUEST = 'hrv/data/SUBJECT_LIST_REQUEST';
export const SUBJECT_LIST_SUCCESS = 'hrv/data/SUBJECT_LIST_SUCCESS';
export const SUBJECT_CREATE_REQUEST = 'hrv/data/SUBJECT_CREATE_REQUEST';
export const SUBJECT_CREATE_SUCCESS = 'hrv/data/SUBJECT_CREATE_SUCCESS';
export const SUBJECT_DESTROY_REQUEST = 'hrv/data/SUBJECT_DESTROY_REQUEST';
export const SUBJECT_DESTROY_SUCCESS = 'hrv/data/SUBJECT_DESTROY_SUCCESS';

export const SESSION_FAILURE = 'hrv/data/SESSION_FAILURE';
export const SESSION_GET_REQUEST = 'hrv/data/SESSION_GET_REQUEST';
export const SESSION_GET_SUCCESS = 'hrv/data/SESSION_GET_SUCCESS';
export const SESSION_LIST_REQUEST = 'hrv/data/SESSION_LIST_REQUEST';
export const SESSION_LIST_SUCCESS = 'hrv/data/SESSION_LIST_SUCCESS';
export const SESSION_CREATE_REQUEST = 'hrv/data/SESSION_CREATE_REQUEST';
export const SESSION_CREATE_SUCCESS = 'hrv/data/SESSION_CREATE_SUCCESS';
export const SESSION_DESTROY_REQUEST = 'hrv/data/SESSION_DESTROY_REQUEST';
export const SESSION_DESTROY_SUCCESS = 'hrv/data/SESSION_DESTROY_SUCCESS';

export const DATASET_FAILURE = 'hrv/data/DATASET_FAILURE';
export const DATASET_GET_REQUEST = 'hrv/data/DATASET_GET_REQUEST';
export const DATASET_GET_SUCCESS = 'hrv/data/DATASET_GET_SUCCESS';
export const DATASET_CREATE_REQUEST = 'hrv/data/DATASET_CREATE_REQUEST';
export const DATASET_CREATE_SUCCESS = 'hrv/data/DATASET_CREATE_SUCCESS';
export const DATASET_DESTROY_REQUEST = 'hrv/data/DATASET_DESTROY_REQUEST';
export const DATASET_DESTROY_SUCCESS = 'hrv/data/DATASET_DESTROY_SUCCESS';
export const DATASET_START_POLLING = 'hrv/data/DATASET_START_POLLING';
export const DATASET_STOP_POLLING = 'hrv/data/DATASET_STOP_POLLING';

export const PREPROCESS_INIT = 'hrv/PREPROCESS_INIT';
export const PREPROCESS_PLOTS_UPSERT = 'hrv/PREPROCESS_PLOTS_UPSERT';
export const PREPROCESS_PLOTS_DELETE = 'hrv/PREPROCESS_PLOTS_DELETE';
export const PREPROCESS_SET_PLOT_MODE = 'hrv/PREPROCESS_SET_PLOT_MODE';
export const PREPROCESS_SET_DOMAIN = 'hrv/PREPROCESS_SET_DOMAIN';
export const PREPROCESS_SET_TAGS = 'hrv/PREPROCESS_SET_TAGS';
